name: "dbt_dagster"
version: "1.0.0"
config-version: 2

profile: "dbt_dagster"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_dagster:
    "0__raw":
      +materialized: table
      +tags: "raw"
      "2019":
        +schema: "2019"
        +tags: "2019"
      "2023":
        +schema: "2023"
        +tags: "2023"
    "1__staging":
      +materialized: view
      +tags: "stg"
      "2019":
        +schema: "2019"
        +tags: "2019"
      "2023":
        +schema: "2023"
        +tags: "2023"
    "2__intermediate":
      +materialized: view
      +enabled: false
    "3__marts":
      +materialized: table
      +tags: "mrt"
      "2019":
        +schema: "2019"
        +tags: "2019"
      "2023":
        +schema: "2023"
        +tags: "2023"
